apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-web
  labels:
    role: web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: web
  template:
    metadata:
      labels:
        role: web
    spec:
      containers:
        - name: infra-web
          image: rutikaaraokar/at-demo:infraweb-amd64
          env:
            - name: ApiAddress
              value: "infra-api.default.svc.cluster.local:5000/WeatherForecast"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000