apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-api
  labels:
    role: api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: infra-api
          image: {{ infra-api image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
